# railway.toml

[build]
builder = "NIXPACKS"   # Use Nixpacks builder
buildCommand = ""      # Optional, can override if needed

[services.backend]
rootDir = "backend"
buildCommand = "./gradlew build -x test"
startCommand = "jjava -jar build/libs/MovieTicketBooking-0.0.1-SNAPSHOT.jar --server.port=$PORT"

[services.frontend]
rootDir = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm run build && npx serve -s dist -l $PORT"

[services.mysql]
plugin = "mysql"
